import type { Product } from "@/types";

export const productsData: Product[] = [
  {
    id: "67729b03-9b34-44a9-95fb-b9a884f01180",
    title: "iPad Pro 13-in. (M4)",
    slug: "ipad-pro-13-in-m4",
    description: "Ultra-thin tablet with OLED display and enhanced multitasking capabilities.",
    category: "tablet",
    price: 1299.99,
    quantity: 14,
    brand: "Apple",
    sku: "APL-IPPR13-M4",
    macAddress: "00:1A:11:3B:45:67",
    serialNumber: "IPPR13M4ZXY9",
    weight: 1.5,
    dimensions: {
      width: 8.46,
      height: 11.04,
      depth: 0.23,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987201",
    images: {
      landscape: {
        png: "/assets/products/landscape/ipad-pro-13-in-m4.png",
        webp: "/assets/products/landscape/ipad-pro-13-in-m4.webp",
      },
      square: {
        png: "/assets/products/square/ipad-pro-13-in-m4.png",
        webp: "/assets/products/square/ipad-pro-13-in-m4.webp",
      },
    },
  },
  {
    id: "d76c423c-1c7a-4d50-b900-0b421c506fdb",
    title: "iPad Air 11-in. (M3)",
    slug: "ipad-air-11-in-m3",
    description: "Lightweight design with improved graphics performance and battery life.",
    category: "tablet",
    price: 699.99,
    quantity: 29,
    brand: "Apple",
    sku: "APL-IPAR11-M3",
    macAddress: "00:1B:22:4C:56:78",
    serialNumber: "IPAR11M3WX45",
    weight: 1.02,
    dimensions: {
      width: 7.03,
      height: 9.74,
      depth: 0.24,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987202",
    images: {
      landscape: {
        png: "/assets/products/landscape/ipad-air-11-in-m3.png",
        webp: "/assets/products/landscape/ipad-air-11-in-m3.webp",
      },
      square: {
        png: "/assets/products/square/ipad-air-11-in-m3.png",
        webp: "/assets/products/square/ipad-air-11-in-m3.webp",
      },
    },
  },
  {
    id: "eb2ce687-3c54-4e78-8676-57c7a4ee5b8e",
    title: "iPad (A16)",
    slug: "ipad-a16",
    description: "Everyday tablet with fast performance and vivid Retina display.",
    category: "tablet",
    price: 449.99,
    quantity: 37,
    brand: "Apple",
    sku: "APL-IPAD-A16",
    macAddress: "00:1C:33:5D:67:89",
    serialNumber: "IPADA16MN03",
    weight: 1.07,
    dimensions: {
      width: 7,
      height: 9.8,
      depth: 0.28,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987203",
    images: {
      landscape: {
        png: "/assets/products/landscape/ipad-a16.png",
        webp: "/assets/products/landscape/ipad-a16.webp",
      },
      square: {
        png: "/assets/products/square/ipad-a16.png",
        webp: "/assets/products/square/ipad-a16.webp",
      },
    },
  },
  {
    id: "d51b8d9c-aa0b-4684-b8b5-714cce9b3863",
    title: "iPad mini (A17 Pro)",
    slug: "ipad-mini-a17-pro",
    description: "Compact form factor with high-performance chip and vivid display.",
    category: "tablet",
    price: 649.99,
    quantity: 21,
    brand: "Apple",
    sku: "APL-IPMN-A17P",
    macAddress: "00:1D:44:6E:78:90",
    serialNumber: "IPMNA17PJK22",
    weight: 0.66,
    dimensions: {
      width: 5.3,
      height: 7.7,
      depth: 0.25,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987204",
    images: {
      landscape: {
        png: "/assets/products/landscape/ipad-mini-a17-pro.png",
        webp: "/assets/products/landscape/ipad-mini-a17-pro.webp",
      },
      square: {
        png: "/assets/products/square/ipad-mini-a17-pro.png",
        webp: "/assets/products/square/ipad-mini-a17-pro.webp",
      },
    },
  },
  {
    id: "78e180cb-b7ed-4fe8-a3a3-d42dbd222de1",
    title: "MacBook Air 13-in. (M4)",
    slug: "macbook-air-13-in-m4",
    description: "Silent fanless laptop with high-efficiency chip and all-day battery.",
    category: "laptop",
    price: 1099.99,
    quantity: 18,
    brand: "Apple",
    sku: "APL-MBA13-M4",
    macAddress: "00:1E:55:7F:89:A1",
    serialNumber: "MBA13M4STU88",
    weight: 2.7,
    dimensions: {
      width: 11.97,
      height: 0.44,
      depth: 8.36,
    },
    releaseDate: "2025-05-07",
    warranty: 24,
    barcode: "194253987205",
    images: {
      landscape: {
        png: "/assets/products/landscape/macbook-air-13-in-m4.png",
        webp: "/assets/products/landscape/macbook-air-13-in-m4.webp",
      },
      square: {
        png: "/assets/products/square/macbook-air-13-in-m4.png",
        webp: "/assets/products/square/macbook-air-13-in-m4.webp",
      },
    },
  },
  {
    id: "48675af5-7935-4497-aaa1-eabb75f62515",
    title: "MacBook Pro 14-in. (M4)",
    slug: "macbook-pro-14-in-m4",
    description: "Pro-level performance in a portable design with XDR display.",
    category: "laptop",
    price: 1999.99,
    quantity: 10,
    brand: "Apple",
    sku: "APL-MBP14-M4",
    macAddress: "00:1F:66:80:9A:B2",
    serialNumber: "MBP14M4ZX01",
    weight: 3.5,
    dimensions: {
      width: 12.31,
      height: 0.61,
      depth: 8.71,
    },
    releaseDate: "2025-05-07",
    warranty: 24,
    barcode: "194253987206",
    images: {
      landscape: {
        png: "/assets/products/landscape/macbook-pro-14-in-m4.png",
        webp: "/assets/products/landscape/macbook-pro-14-in-m4.webp",
      },
      square: {
        png: "/assets/products/square/macbook-pro-14-in-m4.png",
        webp: "/assets/products/square/macbook-pro-14-in-m4.webp",
      },
    },
  },
  {
    id: "d981a27c-b83e-4cfe-8c30-69c10ea7795f",
    title: "MacBook Pro 16-in. (M4 Max)",
    slug: "macbook-pro-16-in-m4-max",
    description: "Maximum performance for intensive workloads and creative tasks.",
    category: "laptop",
    price: 3499.99,
    quantity: 7,
    brand: "Apple",
    sku: "APL-MBP16-M4MX",
    macAddress: "00:20:77:91:AB:C3",
    serialNumber: "MBP16M4MX33",
    weight: 4.8,
    dimensions: {
      width: 14.01,
      height: 0.66,
      depth: 9.77,
    },
    releaseDate: "2025-05-07",
    warranty: 24,
    barcode: "194253987207",
    images: {
      landscape: {
        png: "/assets/products/landscape/macbook-pro-16-in-m4-max.png",
        webp: "/assets/products/landscape/macbook-pro-16-in-m4-max.webp",
      },
      square: {
        png: "/assets/products/square/macbook-pro-16-in-m4-max.png",
        webp: "/assets/products/square/macbook-pro-16-in-m4-max.webp",
      },
    },
  },
  {
    id: "63772b7e-3e18-4af9-9fdb-4937facc7d2e",
    title: "iMac (M4)",
    slug: "imac-m4",
    description: "All-in-one desktop with vibrant 4.5K Retina display and fast performance.",
    category: "desktop",
    price: 1399.99,
    quantity: 16,
    brand: "Apple",
    sku: "APL-IMAC-M4",
    macAddress: "00:21:88:A2:BC:D4",
    serialNumber: "IMACM4XYZ12",
    weight: 9.8,
    dimensions: {
      width: 24.1,
      height: 20.3,
      depth: 5.8,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987208",
    images: {
      landscape: {
        png: "/assets/products/landscape/imac-m4.png",
        webp: "/assets/products/landscape/imac-m4.webp",
      },
      square: {
        png: "/assets/products/square/imac-m4.png",
        webp: "/assets/products/square/imac-m4.webp",
      },
    },
  },
  {
    id: "7c5434e1-8a51-49ea-807a-fb9093d2ec82",
    title: "Mac mini (M4)",
    slug: "mac-mini-m4",
    description: "Compact desktop with silent operation and powerful chip in a small form.",
    category: "desktop",
    price: 699.99,
    quantity: 24,
    brand: "Apple",
    sku: "APL-MMINI-M4",
    macAddress: "00:22:99:B3:CD:E5",
    serialNumber: "MMINIM4AB34",
    weight: 2.6,
    dimensions: {
      width: 7.7,
      height: 1.4,
      depth: 7.7,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987209",
    images: {
      landscape: {
        png: "/assets/products/landscape/mac-mini-m4.png",
        webp: "/assets/products/landscape/mac-mini-m4.webp",
      },
      square: {
        png: "/assets/products/square/mac-mini-m4.png",
        webp: "/assets/products/square/mac-mini-m4.webp",
      },
    },
  },
  {
    id: "539e3051-1ce6-4e74-ad0a-ae8333465d24",
    title: "Mac Studio (M4 Max)",
    slug: "mac-studio-m4-max",
    description: "High-performance desktop for demanding workflows and 3D rendering.",
    category: "desktop",
    price: 2999.99,
    quantity: 11,
    brand: "Apple",
    sku: "APL-MSTU-M4MX",
    macAddress: "00:23:AA:C4:DE:F6",
    serialNumber: "MSTUM4MX567",
    weight: 7.9,
    dimensions: {
      width: 7.7,
      height: 3.7,
      depth: 7.7,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987210",
    images: {
      landscape: {
        png: "/assets/products/landscape/mac-studio-m4-max.png",
        webp: "/assets/products/landscape/mac-studio-m4-max.webp",
      },
      square: {
        png: "/assets/products/square/mac-studio-m4-max.png",
        webp: "/assets/products/square/mac-studio-m4-max.webp",
      },
    },
  },
  {
    id: "282faf9f-c188-4259-9d00-bee067850c91",
    title: "Mac Studio (M3 Ultra)",
    slug: "mac-studio-m3-ultra",
    description: "Ultra-fast desktop for developers, artists, and video professionals.",
    category: "desktop",
    price: 3999.99,
    quantity: 6,
    brand: "Apple",
    sku: "APL-MSTU-M3U",
    macAddress: "00:24:BB:D5:EF:07",
    serialNumber: "MSTUM3ULTRA8",
    weight: 7.9,
    dimensions: {
      width: 7.7,
      height: 3.7,
      depth: 7.7,
    },
    releaseDate: "2025-05-07",
    warranty: 12,
    barcode: "194253987211",
    images: {
      landscape: {
        png: "/assets/products/landscape/mac-studio-m3-ultra.png",
        webp: "/assets/products/landscape/mac-studio-m3-ultra.webp",
      },
      square: {
        png: "/assets/products/square/mac-studio-m3-ultra.png",
        webp: "/assets/products/square/mac-studio-m3-ultra.webp",
      },
    },
  },
  {
    id: "3d224416-8d55-43c5-84e6-dda2ae29ab55",
    title: "Mac Pro (M2 Ultra)",
    slug: "mac-pro-m2-ultra",
    description: "Modular desktop tower built for extreme processing and expansion.",
    category: "desktop",
    price: 6999.99,
    quantity: 4,
    brand: "Apple",
    sku: "APL-MPRO-M2U",
    macAddress: "00:25:CC:E6:F0:18",
    serialNumber: "MPROM2ULTRA9",
    weight: 37.2,
    dimensions: {
      width: 8.7,
      height: 20.8,
      depth: 17.7,
    },
    releaseDate: "2024-06-05",
    warranty: 24,
    barcode: "194253987212",
    images: {
      landscape: {
        png: "/assets/products/landscape/mac-pro-m2-ultra.png",
        webp: "/assets/products/landscape/mac-pro-m2-ultra.webp",
      },
      square: {
        png: "/assets/products/square/mac-pro-m2-ultra.png",
        webp: "/assets/products/square/mac-pro-m2-ultra.webp",
      },
    },
  },
  {
    id: "08fb8da1-2409-404d-a7e1-c6e4462d7106",
    title: "Apple Watch SE (2nd generation)",
    slug: "apple-watch-se-2nd-generation",
    description: "Affordable smartwatch with core health tracking and notifications.",
    category: "watch",
    price: 249.99,
    quantity: 34,
    brand: "Apple",
    sku: "APL-AWSE2-40",
    macAddress: "00:26:DD:F7:01:29",
    serialNumber: "AWSE240MM77",
    weight: 0.06,
    dimensions: {
      width: 1.34,
      height: 1.57,
      depth: 0.42,
    },
    releaseDate: "2024-09-12",
    warranty: 12,
    barcode: "194253987213",
    images: {
      landscape: {
        png: "/assets/products/landscape/apple-watch-se-2nd-generation.png",
        webp: "/assets/products/landscape/apple-watch-se-2nd-generation.webp",
      },
      square: {
        png: "/assets/products/square/apple-watch-se-2nd-generation.png",
        webp: "/assets/products/square/apple-watch-se-2nd-generation.webp",
      },
    },
  },
  {
    id: "711d129c-2e8a-44f9-a2ac-18ca6167b550",
    title: "Apple Watch Series 10",
    slug: "apple-watch-series-10",
    description: "Next-gen smartwatch with larger display and advanced sensors.",
    category: "watch",
    price: 449.99,
    quantity: 22,
    brand: "Apple",
    sku: "APL-AWS10-45",
    macAddress: "00:27:EE:08:12:3A",
    serialNumber: "AWS1045MM88",
    weight: 0.07,
    dimensions: {
      width: 1.46,
      height: 1.76,
      depth: 0.42,
    },
    releaseDate: "2025-09-10",
    warranty: 12,
    barcode: "194253987214",
    images: {
      landscape: {
        png: "/assets/products/landscape/apple-watch-series-10.png",
        webp: "/assets/products/landscape/apple-watch-series-10.webp",
      },
      square: {
        png: "/assets/products/square/apple-watch-series-10.png",
        webp: "/assets/products/square/apple-watch-series-10.webp",
      },
    },
  },
  {
    id: "f7a41ac6-0241-4e5c-a0ea-5b23e160a5b1",
    title: "Apple Watch Ultra 2",
    slug: "apple-watch-ultra-2",
    description: "Rugged smartwatch with extended battery and outdoor tracking tools.",
    category: "watch",
    price: 799.99,
    quantity: 13,
    brand: "Apple",
    sku: "APL-AWU2-49",
    macAddress: "00:28:FF:19:23:4B",
    serialNumber: "AWU249MM99",
    weight: 0.12,
    dimensions: {
      width: 1.72,
      height: 1.99,
      depth: 0.53,
    },
    releaseDate: "2024-09-12",
    warranty: 12,
    barcode: "194253987215",
    images: {
      landscape: {
        png: "/assets/products/landscape/apple-watch-ultra-2.png",
        webp: "/assets/products/landscape/apple-watch-ultra-2.webp",
      },
      square: {
        png: "/assets/products/square/apple-watch-ultra-2.png",
        webp: "/assets/products/square/apple-watch-ultra-2.webp",
      },
    },
  },
  {
    id: "9cee1cb9-8cb7-4a46-9803-6140edad6046",
    title: "iPhone 16 Pro",
    slug: "iphone-16-pro",
    description: "Premium smartphone with advanced display, titanium frame, and powerful camera system.",
    category: "phone",
    price: 1099.99,
    quantity: 31,
    brand: "Apple",
    sku: "APL-IP16P-256",
    macAddress: "00:29:AA:BC:34:56",
    serialNumber: "IP16PROA1234",
    weight: 0.45,
    dimensions: {
      width: 2.81,
      height: 5.81,
      depth: 0.31,
    },
    releaseDate: "2024-09-20",
    warranty: 12,
    barcode: "194253987216",
    images: {
      landscape: {
        png: "/assets/products/landscape/iphone-16-pro.png",
        webp: "/assets/products/landscape/iphone-16-pro.webp",
      },
      square: {
        png: "/assets/products/square/iphone-16-pro.png",
        webp: "/assets/products/square/iphone-16-pro.webp",
      },
    },
  },
  {
    id: "6ac470c5-3e80-494e-b6d9-14282307b946",
    title: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    description: "Large-screen flagship with periscope zoom and top-tier performance.",
    category: "phone",
    price: 1199.99,
    quantity: 22,
    brand: "Apple",
    sku: "APL-IP16PM-512",
    macAddress: "00:2A:BB:CD:45:67",
    serialNumber: "IP16PROMAX5678",
    weight: 0.47,
    dimensions: {
      width: 3.06,
      height: 6.29,
      depth: 0.32,
    },
    releaseDate: "2024-09-20",
    warranty: 12,
    barcode: "194253987217",
    images: {
      landscape: {
        png: "/assets/products/landscape/iphone-16-pro-max.png",
        webp: "/assets/products/landscape/iphone-16-pro-max.webp",
      },
      square: {
        png: "/assets/products/square/iphone-16-pro-max.png",
        webp: "/assets/products/square/iphone-16-pro-max.webp",
      },
    },
  },
  {
    id: "36ecbe4c-6994-49c6-a022-3a4027102621",
    title: "iPhone 16",
    slug: "iphone-16",
    description: "Balanced smartphone with new chip and improved battery life.",
    category: "phone",
    price: 899.99,
    quantity: 38,
    brand: "Apple",
    sku: "APL-IP16-128",
    macAddress: "00:2B:CC:DE:56:78",
    serialNumber: "IP16BASICA9012",
    weight: 0.42,
    dimensions: {
      width: 2.82,
      height: 5.78,
      depth: 0.31,
    },
    releaseDate: "2024-09-20",
    warranty: 12,
    barcode: "194253987218",
    images: {
      landscape: {
        png: "/assets/products/landscape/iphone-16.png",
        webp: "/assets/products/landscape/iphone-16.webp",
      },
      square: {
        png: "/assets/products/square/iphone-16.png",
        webp: "/assets/products/square/iphone-16.webp",
      },
    },
  },
  {
    id: "0b692460-3a86-4981-aec7-15fa49ad9093",
    title: "iPhone 16e",
    slug: "iphone-16e",
    description: "Entry-level option with modern design and essential features.",
    category: "phone",
    price: 699.99,
    quantity: 45,
    brand: "Apple",
    sku: "APL-IP16E-128",
    macAddress: "00:2C:DD:EF:67:89",
    serialNumber: "IP16EASYM3456",
    weight: 0.4,
    dimensions: {
      width: 2.78,
      height: 5.75,
      depth: 0.3,
    },
    releaseDate: "2024-09-20",
    warranty: 12,
    barcode: "194253987219",
    images: {
      landscape: {
        png: "/assets/products/landscape/iphone-16e.png",
        webp: "/assets/products/landscape/iphone-16e.webp",
      },
      square: {
        png: "/assets/products/square/iphone-16e.png",
        webp: "/assets/products/square/iphone-16e.webp",
      },
    },
  },
  {
    id: "99562898-1bb6-47fa-9bf2-3b04943f2ccb",
    title: "AirPods 4",
    slug: "airpods-4",
    description: "Wireless earbuds with improved fit, audio quality, and longer battery life.",
    category: "headphone",
    price: 179.99,
    quantity: 40,
    brand: "Apple",
    sku: "APL-APODS4-WHT",
    macAddress: "00:2D:EE:F0:78:90",
    serialNumber: "APODS4GENM7890",
    weight: 0.12,
    dimensions: {
      width: 0.7,
      height: 1.6,
      depth: 0.7,
    },
    releaseDate: "2024-10-15",
    warranty: 12,
    barcode: "194253987220",
    images: {
      landscape: {
        png: "/assets/products/landscape/airpods-4.png",
        webp: "/assets/products/landscape/airpods-4.webp",
      },
      square: {
        png: "/assets/products/square/airpods-4.png",
        webp: "/assets/products/square/airpods-4.webp",
      },
    },
  },
  {
    id: "451dc028-b4f8-4dae-adc8-8ee51abe67b2",
    title: "AirPods Pro 2",
    slug: "airpods-pro-2",
    description: "Noise-canceling earbuds with adaptive transparency and spatial audio.",
    category: "headphone",
    price: 249.99,
    quantity: 33,
    brand: "Apple",
    sku: "APL-APODS2P-WHT",
    macAddress: "00:2E:FF:01:89:A1",
    serialNumber: "APODSPRO2A1122",
    weight: 0.19,
    dimensions: {
      width: 0.86,
      height: 1.22,
      depth: 0.94,
    },
    releaseDate: "2024-09-20",
    warranty: 12,
    barcode: "194253987221",
    images: {
      landscape: {
        png: "/assets/products/landscape/airpods-pro-2.png",
        webp: "/assets/products/landscape/airpods-pro-2.webp",
      },
      square: {
        png: "/assets/products/square/airpods-pro-2.png",
        webp: "/assets/products/square/airpods-pro-2.webp",
      },
    },
  },
  {
    id: "1fb0fdfd-37ad-4523-b33b-1179500d960e",
    title: "AirPods Max",
    slug: "airpods-max",
    description: "Over-ear headphones with high-fidelity audio and active noise cancellation.",
    category: "headphone",
    price: 549.99,
    quantity: 19,
    brand: "Apple",
    sku: "APL-APMAX-SLV",
    macAddress: "00:2F:00:12:9A:B2",
    serialNumber: "APODSMAXC3344",
    weight: 0.85,
    dimensions: {
      width: 6.6,
      height: 7.4,
      depth: 3.3,
    },
    releaseDate: "2024-11-05",
    warranty: 12,
    barcode: "194253987222",
    images: {
      landscape: {
        png: "/assets/products/landscape/airpods-max.png",
        webp: "/assets/products/landscape/airpods-max.webp",
      },
      square: {
        png: "/assets/products/square/airpods-max.png",
        webp: "/assets/products/square/airpods-max.webp",
      },
    },
  },
  {
    id: "2e59abfe-fe32-4ec8-a0a4-2f8ffc9eee67",
    title: "Pixel 9a",
    slug: "pixel-9a",
    description: "Affordable smartphone with excellent battery life and clean software experience.",
    category: "phone",
    price: 499.99,
    quantity: 42,
    brand: "Google",
    sku: "GGL-PX9A-128",
    macAddress: "10:11:12:13:14:15",
    serialNumber: "PX9A128GG001",
    weight: 0.39,
    dimensions: {
      width: 2.8,
      height: 6,
      depth: 0.3,
    },
    releaseDate: "2025-05-14",
    warranty: 12,
    barcode: "842776123001",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-9a.png",
        webp: "/assets/products/landscape/pixel-9a.webp",
      },
      square: {
        png: "/assets/products/square/pixel-9a.png",
        webp: "/assets/products/square/pixel-9a.webp",
      },
    },
  },
  {
    id: "7b3dde84-f4c4-4421-8a02-910bf21d471a",
    title: "Pixel 9 Pro",
    slug: "pixel-9-pro",
    description: "Premium phone with advanced camera system and smooth OLED display.",
    category: "phone",
    price: 999.99,
    quantity: 26,
    brand: "Google",
    sku: "GGL-PX9P-256",
    macAddress: "20:21:22:23:24:25",
    serialNumber: "PX9PROGG256A",
    weight: 0.43,
    dimensions: {
      width: 2.9,
      height: 6.3,
      depth: 0.3,
    },
    releaseDate: "2025-10-10",
    warranty: 12,
    barcode: "842776123002",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-9-pro.png",
        webp: "/assets/products/landscape/pixel-9-pro.webp",
      },
      square: {
        png: "/assets/products/square/pixel-9-pro.png",
        webp: "/assets/products/square/pixel-9-pro.webp",
      },
    },
  },
  {
    id: "a6c576df-8b32-4a9d-bf63-5b39747646bc",
    title: "Pixel 9 Pro Fold",
    slug: "pixel-9-pro-fold",
    description: "Foldable phone with tablet-sized screen and multitasking features.",
    category: "phone",
    price: 1799.99,
    quantity: 8,
    brand: "Google",
    sku: "GGL-PX9PF-512",
    macAddress: "30:31:32:33:34:35",
    serialNumber: "PX9FOLDGG512X",
    weight: 0.55,
    dimensions: {
      width: 2.9,
      height: 6.2,
      depth: 0.5,
    },
    releaseDate: "2025-10-10",
    warranty: 12,
    barcode: "842776123003",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-9-pro-fold.png",
        webp: "/assets/products/landscape/pixel-9-pro-fold.webp",
      },
      square: {
        png: "/assets/products/square/pixel-9-pro-fold.png",
        webp: "/assets/products/square/pixel-9-pro-fold.webp",
      },
    },
  },
  {
    id: "eccbfef8-6b79-48bd-8063-58bd20e7fa32",
    title: "Pixel 9",
    slug: "pixel-9",
    description: "Well-rounded smartphone with intelligent photography and AI features.",
    category: "phone",
    price: 799.99,
    quantity: 33,
    brand: "Google",
    sku: "GGL-PX9-128",
    macAddress: "40:41:42:43:44:45",
    serialNumber: "PX9BASEGG128B",
    weight: 0.41,
    dimensions: {
      width: 2.8,
      height: 6.1,
      depth: 0.3,
    },
    releaseDate: "2025-10-10",
    warranty: 12,
    barcode: "842776123004",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-9.png",
        webp: "/assets/products/landscape/pixel-9.webp",
      },
      square: {
        png: "/assets/products/square/pixel-9.png",
        webp: "/assets/products/square/pixel-9.webp",
      },
    },
  },
  {
    id: "6dc77f07-b42d-4778-af36-0496350ad0e5",
    title: "Pixel Buds Pro 2",
    slug: "pixel-buds-pro-2",
    description: "Wireless earbuds with active noise cancellation and adaptive sound.",
    category: "headphone",
    price: 229.99,
    quantity: 29,
    brand: "Google",
    sku: "GGL-PBPRO2-BLK",
    macAddress: "50:51:52:53:54:55",
    serialNumber: "PBPRO2GG2025",
    weight: 0.13,
    dimensions: {
      width: 0.9,
      height: 1.2,
      depth: 0.9,
    },
    releaseDate: "2025-07-01",
    warranty: 12,
    barcode: "842776123005",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-buds-pro-2.png",
        webp: "/assets/products/landscape/pixel-buds-pro-2.webp",
      },
      square: {
        png: "/assets/products/square/pixel-buds-pro-2.png",
        webp: "/assets/products/square/pixel-buds-pro-2.webp",
      },
    },
  },
  {
    id: "43835b83-6828-4eea-ab55-25bd50c5c8b0",
    title: "Pixel Buds A-Series",
    slug: "pixel-buds-a-series",
    description: "Affordable wireless earbuds with solid sound and integration features.",
    category: "headphone",
    price: 99.99,
    quantity: 46,
    brand: "Google",
    sku: "GGL-PBAS-WHT",
    macAddress: "60:61:62:63:64:65",
    serialNumber: "PBASGG2024XY",
    weight: 0.12,
    dimensions: {
      width: 0.8,
      height: 1.1,
      depth: 0.8,
    },
    releaseDate: "2024-09-05",
    warranty: 12,
    barcode: "842776123006",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-buds-a-series.png",
        webp: "/assets/products/landscape/pixel-buds-a-series.webp",
      },
      square: {
        png: "/assets/products/square/pixel-buds-a-series.png",
        webp: "/assets/products/square/pixel-buds-a-series.webp",
      },
    },
  },
  {
    id: "c4ac94ed-7501-412e-b420-4d2f9f946282",
    title: "Pixel Tablet",
    slug: "pixel-tablet",
    description: "Versatile tablet with dock integration and smart home control.",
    category: "tablet",
    price: 599.99,
    quantity: 18,
    brand: "Google",
    sku: "GGL-PTAB-128",
    macAddress: "70:71:72:73:74:75",
    serialNumber: "PTABGG128C45",
    weight: 1.1,
    dimensions: {
      width: 10.2,
      height: 6.7,
      depth: 0.3,
    },
    releaseDate: "2024-05-10",
    warranty: 12,
    barcode: "842776123007",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-tablet.png",
        webp: "/assets/products/landscape/pixel-tablet.webp",
      },
      square: {
        png: "/assets/products/square/pixel-tablet.png",
        webp: "/assets/products/square/pixel-tablet.webp",
      },
    },
  },
  {
    id: "ebb1dc07-e902-4da3-af0f-56791c54064a",
    title: "Pixel Watch 3",
    slug: "pixel-watch-3",
    description: "Smartwatch with improved battery, enhanced fitness tracking, and sleek design.",
    category: "watch",
    price: 399.99,
    quantity: 21,
    brand: "Google",
    sku: "GGL-PW3-BLK",
    macAddress: "80:81:82:83:84:85",
    serialNumber: "PWATCH3GG500",
    weight: 0.08,
    dimensions: {
      width: 1.4,
      height: 1.4,
      depth: 0.45,
    },
    releaseDate: "2025-10-10",
    warranty: 12,
    barcode: "842776123008",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-watch-3.png",
        webp: "/assets/products/landscape/pixel-watch-3.webp",
      },
      square: {
        png: "/assets/products/square/pixel-watch-3.png",
        webp: "/assets/products/square/pixel-watch-3.webp",
      },
    },
  },
  {
    id: "32de3c40-8b42-4d9b-a082-bd06d3c4ff47",
    title: "Pixel Watch 2",
    slug: "pixel-watch-2",
    description: "Compact smartwatch with Fitbit integration and safety features.",
    category: "watch",
    price: 349.99,
    quantity: 27,
    brand: "Google",
    sku: "GGL-PW2-SLV",
    macAddress: "90:91:92:93:94:95",
    serialNumber: "PWATCH2GG402",
    weight: 0.07,
    dimensions: {
      width: 1.4,
      height: 1.4,
      depth: 0.43,
    },
    releaseDate: "2024-10-04",
    warranty: 12,
    barcode: "842776123009",
    images: {
      landscape: {
        png: "/assets/products/landscape/pixel-watch-2.png",
        webp: "/assets/products/landscape/pixel-watch-2.webp",
      },
      square: {
        png: "/assets/products/square/pixel-watch-2.png",
        webp: "/assets/products/square/pixel-watch-2.webp",
      },
    },
  },
  {
    id: "dcb3dd22-cccd-45fa-a83c-e0e654dd6550",
    title: "Nest Mini (2nd gen)",
    slug: "nest-mini-2nd-gen",
    description: "Compact smart speaker with better bass and voice recognition.",
    category: "speaker",
    price: 49.99,
    quantity: 36,
    brand: "Google",
    sku: "GGL-NMINI2-GRY",
    macAddress: "A0:A1:A2:A3:A4:A5",
    serialNumber: "NMINI2GG789X",
    weight: 0.43,
    dimensions: {
      width: 3.85,
      height: 1.65,
      depth: 3.85,
    },
    releaseDate: "2024-08-01",
    warranty: 12,
    barcode: "842776123010",
    images: {
      landscape: {
        png: "/assets/products/landscape/nest-mini-2nd-gen.png",
        webp: "/assets/products/landscape/nest-mini-2nd-gen.webp",
      },
      square: {
        png: "/assets/products/square/nest-mini-2nd-gen.png",
        webp: "/assets/products/square/nest-mini-2nd-gen.webp",
      },
    },
  },
  {
    id: "b10b8c9b-6538-4245-9a46-7299215f73ed",
    title: "Nest Audio",
    slug: "nest-audio",
    description: "Smart speaker with rich sound and seamless home assistant support.",
    category: "speaker",
    price: 99.99,
    quantity: 30,
    brand: "Google",
    sku: "GGL-NAUDIO-BLK",
    macAddress: "B0:B1:B2:B3:B4:B5",
    serialNumber: "NAUDIOGG567Z",
    weight: 2.65,
    dimensions: {
      width: 4.89,
      height: 6.89,
      depth: 3.07,
    },
    releaseDate: "2024-08-01",
    warranty: 12,
    barcode: "842776123011",
    images: {
      landscape: {
        png: "/assets/products/landscape/nest-audio.png",
        webp: "/assets/products/landscape/nest-audio.webp",
      },
      square: {
        png: "/assets/products/square/nest-audio.png",
        webp: "/assets/products/square/nest-audio.webp",
      },
    },
  },
  {
    id: "a4ea2b75-5729-4698-84f9-32f468c59f4d",
    title: 'Samsung 65" OLED S95F 4K',
    slug: "samsung-65-oled-s95f-4k",
    description: "Vibrant OLED display with deep blacks and cinematic color accuracy.",
    category: "tv",
    price: 3299.99,
    quantity: 25,
    brand: "Samsung",
    sku: "SMS-S95F42",
    macAddress: "C0:C1:C2:C3:C4:C5",
    serialNumber: "SMS42S95F2025",
    weight: 32.1,
    dimensions: {
      width: 36.7,
      height: 21.1,
      depth: 1.6,
    },
    releaseDate: "2025-03-15",
    warranty: 24,
    barcode: "880609999001",
    images: {
      landscape: {
        png: "/assets/products/landscape/samsung-65-oled-s95f-4k.png",
        webp: "/assets/products/landscape/samsung-65-oled-s95f-4k.webp",
      },
      square: {
        png: "/assets/products/square/samsung-65-oled-s95f-4k.png",
        webp: "/assets/products/square/samsung-65-oled-s95f-4k.webp",
      },
    },
  },
  {
    id: "5594eccd-3428-4f57-bd99-23bdb887d29b",
    title: 'Samsung 50" The Frame LS03FA QLED 4K',
    slug: "samsung-50-the-frame-ls03fa-qled-4k",
    description: "Stylish QLED display designed to blend into home decor with art mode.",
    category: "tv",
    price: 1299.99,
    quantity: 14,
    brand: "Samsung",
    sku: "SMS-LS03FA50",
    macAddress: "D0:D1:D2:D3:D4:D5",
    serialNumber: "SMS50LS03FA2025",
    weight: 38.4,
    dimensions: {
      width: 44.3,
      height: 25.4,
      depth: 1,
    },
    releaseDate: "2025-02-20",
    warranty: 24,
    barcode: "880609999002",
    images: {
      landscape: {
        png: "/assets/products/landscape/samsung-50-the-frame-ls03fa-qled-4k.png",
        webp: "/assets/products/landscape/samsung-50-the-frame-ls03fa-qled-4k.webp",
      },
      square: {
        png: "/assets/products/square/samsung-50-the-frame-ls03fa-qled-4k.png",
        webp: "/assets/products/square/samsung-50-the-frame-ls03fa-qled-4k.webp",
      },
    },
  },
  {
    id: "a2c6056d-c9e7-4e89-9ea2-cffa2740d1e5",
    title: 'Samsung 65" QLED Q7F 4K',
    slug: "samsung-65-qled-q7f-4k",
    description: "Bright QLED panel with wide viewing angles and advanced motion features.",
    category: "tv",
    price: 629.99,
    quantity: 10,
    brand: "Samsung",
    sku: "SMS-Q7F65",
    macAddress: "E0:E1:E2:E3:E4:E5",
    serialNumber: "SMS65Q7F2025",
    weight: 56.9,
    dimensions: {
      width: 57.1,
      height: 32.7,
      depth: 2.3,
    },
    releaseDate: "2025-04-10",
    warranty: 24,
    barcode: "880609999003",
    images: {
      landscape: {
        png: "/assets/products/landscape/samsung-65-qled-q7f-4k.png",
        webp: "/assets/products/landscape/samsung-65-qled-q7f-4k.webp",
      },
      square: {
        png: "/assets/products/square/samsung-65-qled-q7f-4k.png",
        webp: "/assets/products/square/samsung-65-qled-q7f-4k.webp",
      },
    },
  },
  {
    id: "14e50c72-8473-455c-8c1b-a404b216a0c9",
    title: 'Samsung 75" Crystal UHD U8000F 4K',
    slug: "samsung-75-crystal-uhd-u8000f-4k",
    description: "Sharp and affordable UHD display with smart TV features and HDR.",
    category: "tv",
    price: 899.99,
    quantity: 18,
    brand: "Samsung",
    sku: "SMS-U8000F75",
    macAddress: "F0:F1:F2:F3:F4:F5",
    serialNumber: "SMS75U8000F2025",
    weight: 68.3,
    dimensions: {
      width: 65.9,
      height: 37.8,
      depth: 2.4,
    },
    releaseDate: "2025-01-25",
    warranty: 24,
    barcode: "880609999004",
    images: {
      landscape: {
        png: "/assets/products/landscape/samsung-75-crystal-uhd-u8000f-4k.png",
        webp: "/assets/products/landscape/samsung-75-crystal-uhd-u8000f-4k.webp",
      },
      square: {
        png: "/assets/products/square/samsung-75-crystal-uhd-u8000f-4k.png",
        webp: "/assets/products/square/samsung-75-crystal-uhd-u8000f-4k.webp",
      },
    },
  },
  {
    id: "005d5ea3-7620-43de-96ba-934710bc2612",
    title: 'LG 55" UHD 4K',
    slug: "lg-55-uhd-4k",
    description: "Reliable UHD screen with crisp visuals and intuitive webOS interface.",
    category: "tv",
    price: 599.99,
    quantity: 22,
    brand: "LG",
    sku: "LG-UHD4K55",
    macAddress: "01:11:21:31:41:51",
    serialNumber: "LG55UHD4K2025",
    weight: 35.6,
    dimensions: {
      width: 48.7,
      height: 28.2,
      depth: 2.2,
    },
    releaseDate: "2025-02-12",
    warranty: 24,
    barcode: "880609999005",
    images: {
      landscape: {
        png: "/assets/products/landscape/lg-55-uhd-4k.png",
        webp: "/assets/products/landscape/lg-55-uhd-4k.webp",
      },
      square: {
        png: "/assets/products/square/lg-55-uhd-4k.png",
        webp: "/assets/products/square/lg-55-uhd-4k.webp",
      },
    },
  },
  {
    id: "a3997809-9d64-40dc-9995-d061ad1f88f4",
    title: 'LG 55" OLED evo C5 4K',
    slug: "lg-55-oled-evo-c5-4k",
    description: "Next-gen OLED evo panel offering exceptional contrast and clarity.",
    category: "tv",
    price: 1499.99,
    quantity: 12,
    brand: "LG",
    sku: "LG-C5OLED55",
    macAddress: "02:12:22:32:42:52",
    serialNumber: "LG55C5OLED2025",
    weight: 41.2,
    dimensions: {
      width: 48.3,
      height: 27.8,
      depth: 1.8,
    },
    releaseDate: "2025-03-05",
    warranty: 24,
    barcode: "880609999006",
    images: {
      landscape: {
        png: "/assets/products/landscape/lg-55-oled-evo-c5-4k.png",
        webp: "/assets/products/landscape/lg-55-oled-evo-c5-4k.webp",
      },
      square: {
        png: "/assets/products/square/lg-55-oled-evo-c5-4k.png",
        webp: "/assets/products/square/lg-55-oled-evo-c5-4k.webp",
      },
    },
  },
  {
    id: "d56d1c03-26c4-4fa1-8c9c-e782f2fcf693",
    title: 'LG 65" OLED G5 4K',
    slug: "lg-65-oled-g5-4k",
    description: "High-end OLED TV with gallery design and advanced processing.",
    category: "tv",
    price: 2399.99,
    quantity: 9,
    brand: "LG",
    sku: "LG-G5OLED65",
    macAddress: "03:13:23:33:43:53",
    serialNumber: "LG65G5OLED2025",
    weight: 55.8,
    dimensions: {
      width: 57,
      height: 32.6,
      depth: 1,
    },
    releaseDate: "2025-03-28",
    warranty: 24,
    barcode: "880609999007",
    images: {
      landscape: {
        png: "/assets/products/landscape/lg-65-oled-g5-4k.png",
        webp: "/assets/products/landscape/lg-65-oled-g5-4k.webp",
      },
      square: {
        png: "/assets/products/square/lg-65-oled-g5-4k.png",
        webp: "/assets/products/square/lg-65-oled-g5-4k.webp",
      },
    },
  },
  {
    id: "bab4b313-fe83-498b-b414-dfed8f63ebaf",
    title: 'LG 75" QNED 8K',
    slug: "lg-75-qned-8k",
    description: "Cutting-edge 8K display with quantum dot and NanoCell technologies.",
    category: "tv",
    price: 3499.99,
    quantity: 6,
    brand: "LG",
    sku: "LG-QNED8K75",
    macAddress: "04:14:24:34:44:54",
    serialNumber: "LG75QNED8K2025",
    weight: 78.9,
    dimensions: {
      width: 66.1,
      height: 38.1,
      depth: 2.5,
    },
    releaseDate: "2025-04-18",
    warranty: 24,
    barcode: "880609999008",
    images: {
      landscape: {
        png: "/assets/products/landscape/lg-75-qned-8k.png",
        webp: "/assets/products/landscape/lg-75-qned-8k.webp",
      },
      square: {
        png: "/assets/products/square/lg-75-qned-8k.png",
        webp: "/assets/products/square/lg-75-qned-8k.webp",
      },
    },
  },
];
